CREATE TABLE book_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    book_id INT UNSIGNED NOT NULL,
    order_id INT UNSIGNED,
    code VARCHAR(50) NOT NULL,
    reserved_at DATETIME,
    created_at TIMESTAMP NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
